service: nodejs-serverless-typescript-prisma

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL, ''}
    NODE_ENV: ${env:NODE_ENV, 'development'}
    JWT_SECRET: ${env:JWT_SECRET, ''}
    PORT: ${env:PORT, '3000'}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    CORS_ORIGIN: ${env:CORS_ORIGIN, '*'}

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
  dotenv:
    path: ./.env
    basePath: ./
    include:
      - DATABASE_URL
      - NODE_ENV
      - JWT_SECRET
      - PORT
      - LOG_LEVEL
      - CORS_ORIGIN
    logging: false
    required:
      - DATABASE_URL
      - JWT_SECRET

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
