name: AWS Secrets Manager Setup

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Environment to setup secrets for'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      env_file:
        description: 'Local .env file to upload (relative to repo root)'
        required: true
        default: 'env.example'
        type: string

jobs:
  setup-secrets:
    name: Setup Secrets in AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check if .env file exists
        run: |
          if [ ! -f "${{ github.workspace }}/${{ github.event.inputs.env_file }}" ]; then
            echo "::error::The specified .env file does not exist: ${{ github.event.inputs.env_file }}"
            exit 1
          fi

      - name: Create or update secret in AWS Secrets Manager
        run: |
          ENV_SECRET_NAME="env-${{ github.event.inputs.stage }}"

          # Read the env file content
          ENV_CONTENT=$(cat "${{ github.workspace }}/${{ github.event.inputs.env_file }}")

          # Check if secret already exists
          if aws secretsmanager describe-secret --secret-id "$ENV_SECRET_NAME" 2>/dev/null; then
            echo "Secret $ENV_SECRET_NAME already exists. Updating..."
            aws secretsmanager update-secret --secret-id "$ENV_SECRET_NAME" --secret-string "$ENV_CONTENT"
          else
            echo "Creating new secret $ENV_SECRET_NAME..."
            aws secretsmanager create-secret --name "$ENV_SECRET_NAME" --description "Environment variables for ${{ github.event.inputs.stage }}" --secret-string "$ENV_CONTENT"
          fi

          echo "✅ Secret $ENV_SECRET_NAME successfully created/updated in AWS Secrets Manager"
